# Generated by Django 5.1.7 on 2025-03-16 12:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='datasets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dataset_table',
            },
        ),
        migrations.CreateModel(
            name='Densenet_model',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False)),
                ('model_accuracy', models.CharField(default='85.0', max_length=10)),
            ],
            options={
                'db_table': 'Densenet_model',
            },
        ),
        migrations.CreateModel(
            name='MobileNet_model',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False)),
                ('model_accuracy', models.CharField(default='90.0', max_length=10)),
            ],
            options={
                'db_table': 'MobileNet_model',
            },
        ),
        migrations.CreateModel(
            name='resnet_model',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False)),
                ('model_accuracy', models.CharField(default='88.0', max_length=10)),
            ],
            options={
                'db_table': 'resnet_model',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_password', models.TextField(help_text='user_password', max_length=50)),
                ('photo', models.ImageField(upload_to='user_photos/')),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(default='Pending', max_length=15)),
                ('otp_num', models.IntegerField()),
                ('Otp_Status', models.TextField(default='pending', max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_image', models.ImageField(upload_to='fine_images/')),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_response', models.CharField(default='Pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='adminapp.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('Feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('Rating', models.CharField(max_length=100, null=True)),
                ('Review', models.CharField(max_length=225, null=True)),
                ('Sentiment', models.CharField(max_length=100, null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('Reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.userdetails')),
            ],
            options={
                'db_table': 'feedback_details',
            },
        ),
    ]
