# Generated by Django 5.1.7 on 2025-03-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarthquakePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdi', models.FloatField()),
                ('nst', models.IntegerField()),
                ('depth', models.FloatField()),
                ('magnitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('year', models.IntegerField()),
                ('predicted_magnitude_class', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloodPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monsoon_intensity', models.IntegerField()),
                ('topography_drainage', models.IntegerField()),
                ('river_management', models.IntegerField()),
                ('deforestation', models.IntegerField()),
                ('urbanization', models.IntegerField()),
                ('climate_change', models.IntegerField()),
                ('dams_quality', models.IntegerField()),
                ('siltation', models.IntegerField()),
                ('agricultural_practices', models.IntegerField()),
                ('encroachments', models.IntegerField()),
                ('ineffective_disaster_preparedness', models.IntegerField()),
                ('drainage_systems', models.IntegerField()),
                ('coastal_vulnerability', models.IntegerField()),
                ('landslides', models.IntegerField()),
                ('watersheds', models.IntegerField()),
                ('deteriorating_infrastructure', models.IntegerField()),
                ('population_score', models.IntegerField()),
                ('wetland_loss', models.IntegerField()),
                ('inadequate_planning', models.IntegerField()),
                ('political_factors', models.IntegerField()),
                ('prediction_value', models.FloatField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('sentiment', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('dew_point_temp', models.FloatField()),
                ('relative_humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('visibility', models.FloatField()),
                ('pressure', models.FloatField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('predicted_weather', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
